<a href="https://colab.research.google.com/github/deboratech/analise_de_dados/blob/main/bike_sharing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>



```
# An√°lise de Dados
```

In [76]:
import numpy as np
import pandas as pd

In [77]:
df = pd.read_csv("/content/bike-sharing.csv")

In [78]:
print(df)

         datetime  rec_id  season  year  month  hour  is_holiday  weekday  \
0      2011-01-01       1       1     0      1     0           0        6
1      2011-01-01       2       1     0      1     1           0        6
2      2011-01-01       3       1     0      1     2           0        6
3      2011-01-01       4       1     0      1     3           0        6
4      2011-01-01       5       1     0      1     4           0        6
...           ...     ...     ...   ...    ...   ...         ...      ...
17374  2012-12-31   17375       1     1     12    19           0        1
17375  2012-12-31   17376       1     1     12    20           0        1
17376  2012-12-31   17377       1     1     12    21           0        1
17377  2012-12-31   17378       1     1     12    22           0        1
17378  2012-12-31   17379       1     1     12    23           0        1

       is_workingday  weather_condition  temp   atemp  humidity  windspeed  \
0                  0                  1  0.24  0.2879      0.81     0.0000
1                  0                  1  0.22  0.2727      0.80     0.0000
2                  0                  1  0.22  0.2727      0.80     0.0000
3                  0                  1  0.24  0.2879      0.75     0.0000
4                  0                  1  0.24  0.2879      0.75     0.0000
...              ...                ...   ...     ...       ...        ...
17374              1                  2  0.26  0.2576      0.60     0.1642
17375              1                  2  0.26  0.2576      0.60     0.1642
17376              1                  1  0.26  0.2576      0.60     0.1642
17377              1                  1  0.26  0.2727      0.56     0.1343
17378              1                  1  0.26  0.2727      0.65     0.1343

       casual  registered  total_count
0           3          13           16
1           8          32           40
2           5          27           32
3           3          10           13
4           0           1            1
...       ...         ...          ...
17374      11         108          119
17375       8          81           89
17376       7          83           90
17377      13          48           61
17378      12          37           49

[17379 rows x 17 columns]

In [79]:
df.head()

,datetime,rec_id,season,year,month,hour,is_holiday,weekday,is_workingday,weather_condition,temp,atemp,humidity,windspeed,casual,registered,total_count
0,2011-01-01,1,1,0,1,0,0,6,0,1,0.24,0.2879,0.81,0.0,3,13,16
1,2011-01-01,2,1,0,1,1,0,6,0,1,0.22,0.2727,0.80,0.0,8,32,40
2,2011-01-01,3,1,0,1,2,0,6,0,1,0.22,0.2727,0.80,0.0,5,27,32
3,2011-01-01,4,1,0,1,3,0,6,0,1,0.24,0.2879,0.75,0.0,3,10,13
4,2011-01-01,5,1,0,1,4,0,6,0,1,0.24,0.2879,0.75,0.0,0,1,1

In [80]:
df.tail()

,datetime,rec_id,season,year,month,hour,is_holiday,weekday,is_workingday,weather_condition,temp,atemp,humidity,windspeed,casual,registered,total_count
17374,2012-12-31,17375,1,1,12,19,0,1,1,2,0.26,0.2576,0.60,0.1642,11,108,119
17375,2012-12-31,17376,1,1,12,20,0,1,1,2,0.26,0.2576,0.60,0.1642,8,81,89
17376,2012-12-31,17377,1,1,12,21,0,1,1,1,0.26,0.2576,0.60,0.1642,7,83,90
17377,2012-12-31,17378,1,1,12,22,0,1,1,1,0.26,0.2727,0.56,0.1343,13,48,61
17378,2012-12-31,17379,1,1,12,23,0,1,1,1,0.26,0.2727,0.65,0.1343,12,37,49

In [81]:
df = pd.DataFrame(df)
display(df)

,datetime,rec_id,season,year,month,hour,is_holiday,weekday,is_workingday,weather_condition,temp,atemp,humidity,windspeed,casual,registered,total_count
0,2011-01-01,1,1,0,1,0,0,6,0,1,0.24,0.2879,0.81,0.0000,3,13,16
1,2011-01-01,2,1,0,1,1,0,6,0,1,0.22,0.2727,0.80,0.0000,8,32,40
2,2011-01-01,3,1,0,1,2,0,6,0,1,0.22,0.2727,0.80,0.0000,5,27,32
3,2011-01-01,4,1,0,1,3,0,6,0,1,0.24,0.2879,0.75,0.0000,3,10,13
4,2011-01-01,5,1,0,1,4,0,6,0,1,0.24,0.2879,0.75,0.0000,0,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17374,2012-12-31,17375,1,1,12,19,0,1,1,2,0.26,0.2576,0.60,0.1642,11,108,119
17375,2012-12-31,17376,1,1,12,20,0,1,1,2,0.26,0.2576,0.60,0.1642,8,81,89
17376,2012-12-31,17377,1,1,12,21,0,1,1,1,0.26,0.2576,0.60,0.1642,7,83,90
17377,2012-12-31,17378,1,1,12,22,0,1,1,1,0.26,0.2727,0.56,0.1343,13,48,61
17378,2012-12-31,17379,1,1,12,23,0,1,1,1,0.26,0.2727,0.65,0.1343,12,37,49

In [82]:
df= df.drop_duplicates()
df= df.dropna()
display(df)

,datetime,rec_id,season,year,month,hour,is_holiday,weekday,is_workingday,weather_condition,temp,atemp,humidity,windspeed,casual,registered,total_count
0,2011-01-01,1,1,0,1,0,0,6,0,1,0.24,0.2879,0.81,0.0000,3,13,16
1,2011-01-01,2,1,0,1,1,0,6,0,1,0.22,0.2727,0.80,0.0000,8,32,40
2,2011-01-01,3,1,0,1,2,0,6,0,1,0.22,0.2727,0.80,0.0000,5,27,32
3,2011-01-01,4,1,0,1,3,0,6,0,1,0.24,0.2879,0.75,0.0000,3,10,13
4,2011-01-01,5,1,0,1,4,0,6,0,1,0.24,0.2879,0.75,0.0000,0,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17374,2012-12-31,17375,1,1,12,19,0,1,1,2,0.26,0.2576,0.60,0.1642,11,108,119
17375,2012-12-31,17376,1,1,12,20,0,1,1,2,0.26,0.2576,0.60,0.1642,8,81,89
17376,2012-12-31,17377,1,1,12,21,0,1,1,1,0.26,0.2576,0.60,0.1642,7,83,90
17377,2012-12-31,17378,1,1,12,22,0,1,1,1,0.26,0.2727,0.56,0.1343,13,48,61
17378,2012-12-31,17379,1,1,12,23,0,1,1,1,0.26,0.2727,0.65,0.1343,12,37,49

In [83]:
df= df.replace([float('NaN')],'-')

# a. Qual o tamanho desse dataset?

In [84]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 17379 entries, 0 to 17378
Data columns (total 17 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   datetime           17379 non-null  object
 1   rec_id             17379 non-null  int64
 2   season             17379 non-null  int64
 3   year               17379 non-null  int64
 4   month              17379 non-null  int64
 5   hour               17379 non-null  int64
 6   is_holiday         17379 non-null  int64
 7   weekday            17379 non-null  int64
 8   is_workingday      17379 non-null  int64
 9   weather_condition  17379 non-null  int64
 10  temp               17379 non-null  float64
 11  atemp              17379 non-null  float64
 12  humidity           17379 non-null  float64
 13  windspeed          17379 non-null  float64
 14  casual             17379 non-null  int64
 15  registered         17379 non-null  int64
 16  total_count        17379 non-null  int64
dtypes: float64(4), int64(12), object(1)
memory usage: 2.4+ MB

# b. Qual a m√©dia da coluna windspeed?

In [85]:
media = df['windspeed'].mean()
print("A m√©dia da coluna √©:", media)

A m√©dia da coluna √©: 0.19009760630646177

# c. Qual a m√©dia da coluna temp?

In [86]:
media = df['temp'].mean()
print("A m√©dia da coluna √©:", media)

A m√©dia da coluna √©: 0.4969871684216583

# d. Quantos registros existem para o ano de 2011?

In [87]:
df['datetime'] = pd.to_datetime(df['datetime'])
df['year'] = df['datetime'].dt.year
registros_2011 = len(df[df['year'] == 2011])
print("O n√∫mero de registros para o ano de 2011 √©:", registros_2011)

O n√∫mero de registros para o ano de 2011 √©: 8645

# e. Quantos registros existem para o ano de 2012?

In [88]:
df['datetime'] = pd.to_datetime(df['datetime'])
df['year'] = df['datetime'].dt.year
registros_2011 = len(df[df['year'] == 2012])
print("O n√∫mero de registros para o ano de 2012 √©:", registros_2012)

O n√∫mero de registros para o ano de 2012 √©: 8734

#f. Quantas loca√ß√µes de bicicletas foram efetuadas em 2011?

In [89]:
locacoes_2011 = df[df['year'] == 2011]['total_count'].sum()
print("Foram efetuadas", locacoes_2011, "loca√ß√µes de bicicletas em 2011")

Foram efetuadas 1243103 loca√ß√µes de bicicletas em 2011

# g. Qual esta√ß√£o do ano cont√©m a maior m√©dia de loca√ß√µes de bicicletas?

In [90]:
grupo_por_estacao = df.groupby('season')
media_por_estacao = grupo_por_estacao['total_count'].mean()
estacao_mais_alta = media_por_estacao.idxmax()
print("Esta√ß√£o com a maior m√©dia de loca√ß√µes de bicicletas:", estacao_mais_alta)

Esta√ß√£o com a maior m√©dia de loca√ß√µes de bicicletas: 3

# h. Qual esta√ß√£o do ano cont√©m a menor m√©dia de loca√ß√µes de bicicletas?

In [91]:
grupo_por_estacao = df.groupby('season')
media_por_estacao = grupo_por_estacao['total_count'].mean()
estacao_mais_baixa = media_por_estacao.idxmin()
print("Esta√ß√£o com a menor m√©dia de loca√ß√µes de bicicletas:", estacao_mais_baixa)

Esta√ß√£o com a menor m√©dia de loca√ß√µes de bicicletas: 1

#i. Qual hor√°rio do dia cont√©m a maior m√©dia de loca√ß√µes de bicicletas?

In [92]:
grupo_por_hora = df.groupby('hour')
media_por_hora = grupo_por_hora['total_count'].mean()
horario_mais_alto = media_por_hora.idxmax()
print("O hor√°rio que cont√©m a maior m√©dia de loca√ß√µes de bicicletas √©:", horario_mais_alto,"h")

O hor√°rio que cont√©m a maior m√©dia de loca√ß√µes de bicicletas √©: 17 h

#j. Qual hor√°rio do dia cont√©m a menor m√©dia de loca√ß√µes de bicicletas?

In [93]:
grupo_por_hora = df.groupby('hour')
media_por_hora = grupo_por_hora['total_count'].mean()
horario_mais_baixo = media_por_hora.idxmin()
print("O hor√°rio que cont√©m a menor m√©dia de loca√ß√µes de bicicletas √©:", horario_mais_baixo,"h")

O hor√°rio que cont√©m a menor m√©dia de loca√ß√µes de bicicletas √©: 4 h

#k. Que dia da semana cont√©m a maior m√©dia de loca√ß√µes de bicicletas?

In [94]:
df['datetime'] = pd.to_datetime(df['datetime'])
df['dia_semana'] = df['datetime'].dt.day_name()
grupo_por_dia_semana = df.groupby('dia_semana')
media_por_dia_semana = grupo_por_dia_semana['total_count'].mean()
dia_mais_alto = media_por_dia_semana.idxmax()
print("Dia da semana com a maior m√©dia de loca√ß√µes de bicicletas √©:", dia_mais_alto)

Dia da semana com a maior m√©dia de loca√ß√µes de bicicletas √©: Thursday

#l. Que dia da semana cont√©m a menor m√©dia de loca√ß√µes de bicicletas?

In [95]:
df['datetime'] = pd.to_datetime(df['datetime'])
df['dia_semana'] = df['datetime'].dt.day_name()
grupo_por_dia_semana = df.groupby('dia_semana')
media_por_dia_semana = grupo_por_dia_semana['total_count'].mean()
dia_mais_baixo = media_por_dia_semana.idxmin()
print("Dia da semana com a menor m√©dia de loca√ß√µes de bicicletas √©:", dia_mais_baixo)

Dia da semana com a menor m√©dia de loca√ß√µes de bicicletas √©: Sunday

#m. √Äs quartas-feiras (weekday = 3), qual o hor√°rio do dia que cont√©m a maior m√©dia de loca√ß√µes de bicicletas?

In [96]:
quartas_feiras = df[df['weekday'] == 3]
grupo_por_hora = quartas_feiras.groupby('hour')
media_por_hora = grupo_por_hora['total_count'].mean()
horario_mais_alto = media_por_hora.idxmax()
print("Hor√°rio do dia com a maior m√©dia de loca√ß√µes de bicicletas √†s quartas-feiras √©:", horario_mais_alto, "h")

Hor√°rio do dia com a maior m√©dia de loca√ß√µes de bicicletas √†s quartas-feiras √©: 17 h

#n. Aos s√°bados (weekday = 6), qual o hor√°rio do dia que cont√©m a maior m√©dia de loca√ß√µes de bicicletas?

In [97]:
sabados = df[df['weekday'] == 6]
grupo_por_hora = sabados.groupby('hour')
media_por_hora = grupo_por_hora['total_count'].mean()
horario_mais_alto = media_por_hora.idxmax()
print("Hor√°rio do dia com a maior m√©dia de loca√ß√µes de bicicletas aos s√°bados √©:", horario_mais_alto, "h")

Hor√°rio do dia com a maior m√©dia de loca√ß√µes de bicicletas aos s√°bados √©: 13 h